services:
  - type: web
    name: ligakit
    runtime: docker
    region: frankfurt
    plan: free

    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        value: file:/var/data/dev.db
      - key: UPLOAD_DIR
        value: /var/data/uploads
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false

    disk:
      name: ligakit-data
      mountPath: /var/data
      sizeGB: 1
