services:
  - type: web
    name: ligakit
    runtime: docker
    region: frankfurt
    plan: free

    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
